backend:
  name: git-gateway
  branch: master

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/home/index.md"
        slug: "{{slug}}"
        fields:
        - {label: "Content Type", required: false, name: "contentType", widget: "hidden", default: "home"}
        - {label: "Path", required: false, name: "path", widget: "hidden", default: "/"}
        - {label: Title, required: false, name: title, widget: "string"}
        - {label: Cta Copy, required: false, name: cta_copy, widget: "markdown"}
      - label: "Expertise Page"
        name: "expertise"
        file: "src/pages/expertise/expertise.md"
        slug: "{{slug}}"
        fields:
        - {label: "Content Type", required: false, name: "contentType", widget: "hidden", default: "expertise"}
        - {label: "Path", required: false, name: "path", widget: "hidden", default: "/expertise"}
        - {label: Title, required: false, name: title, widget: "string"}
        - {label: Page Header, required: false, name: page_header, widget: "markdown"}
        - label: Expertise
          name: expertise
          widget: list
          fields:
          - {label: Title, name: title, widget: string}
          - {label: Header Copy, name: header, widget: markdown}
          - {label: Body Copy, name: copy, widget: markdown}
          - {label: Sidebar Photo, name: photo, widget: image}

      - label: "The Team Page"
        name: "team"
        file: "src/pages/team/team.md"
        slug: "{{slug}}"
        fields:
        - {label: "Content Type", required: false, name: "contentType", widget: "hidden", default: "team"}
        - {label: "Path", required: false, name: "path", widget: "hidden", default: "/team"}
        - {label: Title, required: false, name: title, widget: "string"}
        - {label: Page Header, required: false, name: page_header, widget: "markdown"}

  - name: "news"
    label: "News"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "blog"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Attachment", name: "attachments", widget: "list", fields: [{name: "filename", label: "Filename", widget: "file"}] }
      - {label: "Related Post", name: "related", widget: "list", fields: [{name: "post", label: "Post", widget: "relation", collection: "blog", searchFields: [name, path, title], valueField: path}] }

  - name: "about"
    label: "About"  
    folder: "src/pages/about" 
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "about"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
