backend:
  name: git-gateway
  branch: master

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/home/index.md"
        slug: "{{slug}}"
        fields:
        - {label: "Content Type", required: false, name: "contentType", widget: "hidden", default: "home"}
        - {label: "Path", required: false, name: "path", widget: "hidden", default: "/"}
        - {label: Title, required: false, name: title, widget: "string"}
        - {label: Cta Copy, required: false, name: cta_copy, widget: "markdown"}
        
      - label: "Expertise Page"
        name: "expertise"
        file: "src/pages/expertise/expertise.md"
        slug: "{{slug}}"
        fields:
        - {label: "Content Type", required: false, name: "contentType", widget: "hidden", default: "expertise"}
        - {label: "Path", required: false, name: "path", widget: "hidden", default: "/expertise"}
        - {label: Title, required: false, name: title, widget: "string"}
        - {label: Page Header, required: false, name: page_header, widget: "markdown"}
        - label: Expertise
          name: expertises
          widget: list
          fields:
          - {label: Title, name: title, widget: string}
          - {label: Header Copy, name: header, widget: markdown}
          - {label: Body Copy, name: copy, widget: markdown}
          - {label: Sidebar Photo, name: photo, widget: image}
          

      - label: "The Team Page"
        name: "team"
        file: "src/pages/team/team.md"
        slug: "{{slug}}"
        fields:
        - {label: "Content Type", required: false, name: "contentType", widget: "hidden", default: "team"}
        - {label: "Path", required: false, name: "path", widget: "hidden", default: "/team"}
        - {label: Title, required: false, name: title, widget: "string"}
        - {label: Page Header, required: false, name: page_header, widget: "markdown"}
        - label: "Team Member"
          name: "team_member"
          widget: "list"
          fields:
          - {label: Name, name: name, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Portrait, name: portrait, widget: image}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Details, name: details, widget: markdown}
          - label: "Team Category"
            name: "category_team"
            widget: "select"
            options: ["Leadership", "Research", "Sales"]

      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact/contact.md"
        slug: "{slug}"
        fields:
        - {label: "Content Type", required: false, name: "contentType", widget: "hidden", default: "contact"}
        - {label: "Path", required: false, name: "path", widget: "hidden", default: "/contact"}
        - {label: Title, required: false, name: title, widget: "string"}
        - {label: Page Header, required: false, name: page_header, widget: "markdown"}
          
  - name: "research"
    label: "Research"
    folder: "src/pages/research"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Attachment", required: false, name: "attachments", widget: "list", fields: [{name: "filename", label: "Filename", widget: "file"}] }
      - {label: "Related Post", required: false, name: "related", widget: "list", fields: [{name: "post", label: "Post", widget: "relation", collection: "blog", searchFields: [name, path, title], valueField: path}] }
      - label: "Categories"
        name: "categories"
        widget: "list"
        fields:
        - label: "Category"
          name: "category"
          widget: "select"
          options: ["Height In The News", "News Feed", "Press Release", "Energy & Environment", "Financial Services", "Healthcare", "Macroeconomics & Sovereign Events", "Special Situations", "Tax & Budget", "Technology, Media & Telecom"]

            
  - name: "teamMembers"
    label: "Team Members"
    folder: "src/pages/team_member"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "team_member"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: Name, name: name, widget: string}
      - {label: Title, name: title, widget: string}
      - {label: Portrait, name: portrait, widget: image}
      - {label: Email, name: email, widget: string}
      - {label: Twitter, name: twitter, widget: string}
      - {label: LinkedIn, name: linkedin, widget: string}
      - {label: Intro, name: intro, widget: markdown}
      - {label: Details, name: details, widget: markdown}
      - label: "Team Category"
        name: "category_team"
        widget: "select"
        options: ["Leadership", "Research", "Sales"]
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields: 
        - {label: Tag Name, name: "tagName", widget: string}
